###
GET http://localhost:8888/user/1 HTTP/1.1

###
PUT http://localhost:8888/user/1 HTTP/1.1

{
    "username": "sascha",
    "password": "foobar"
}

###
DELETE http://localhost:8888/user/1 HTTP/1.1

###
POST http://localhost:8888/user HTTP/1.1

{
    "username": "sascha",
    "password": "foobar"
}












###
POST http://localhost:8888/token HTTP/1.1

{
    "username": "sascha",
    "password": "foobar"
}