GET http://localhost:8888/user HTTP/1.1
Authorization: Basic am9yaXM6c3VwZXIxMjM0IQ==


###

GET http://localhost:8888/user HTTP/1.1
Authorization: Basic am9yaXM6c3VwZXIxMjM0IQ==


###
POST http://localhost:8888/user HTTP/1.1
Content-Type: application/json

{"username": "joris", "password": "super1234!"}
###


GET http://localhost:8888/user HTTP/1.1
Authorization: Bearer am9yaXM6c3VwZXIxMjM0IQ==

###
POST http://localhost:8888/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOiJUdWUgSmFuIDE1IDIxOjI1OjA5IDIwMTlcbiIsInJvbGUiOiJBZG1pbiIsInVzZXIiOiJzYXNjaGEifQ.xTR7A7dqT322tElSin1J7oNKhlfBEkG8yTHdcCVT7jQ

{
    "username": "sascha",
    "password": "foobar"
}

###
POST http://localhost:8888/token HTTP/1.1

{
    "username": "sascha",
    "password": "foobar"
}